# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from l3store.api.proto import l3_service_pb2 as l3store_dot_api_dot_proto_dot_l3__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in l3store/api/proto/l3_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class L3ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutKVBlock = channel.unary_unary(
                '/l3store.v1.L3Service/PutKVBlock',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockResponse.FromString,
                _registered_method=True)
        self.GetKVBlock = channel.unary_unary(
                '/l3store.v1.L3Service/GetKVBlock',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockResponse.FromString,
                _registered_method=True)
        self.DeleteKVBlock = channel.unary_unary(
                '/l3store.v1.L3Service/DeleteKVBlock',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockResponse.FromString,
                _registered_method=True)
        self.ListKVBlocks = channel.unary_unary(
                '/l3store.v1.L3Service/ListKVBlocks',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksResponse.FromString,
                _registered_method=True)
        self.PutRAGObject = channel.unary_unary(
                '/l3store.v1.L3Service/PutRAGObject',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectResponse.FromString,
                _registered_method=True)
        self.GetRAGObject = channel.unary_unary(
                '/l3store.v1.L3Service/GetRAGObject',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectResponse.FromString,
                _registered_method=True)
        self.PutSemanticEntry = channel.unary_unary(
                '/l3store.v1.L3Service/PutSemanticEntry',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryResponse.FromString,
                _registered_method=True)
        self.GetSemanticEntry = channel.unary_unary(
                '/l3store.v1.L3Service/GetSemanticEntry',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryResponse.FromString,
                _registered_method=True)
        self.SearchSimilarPrompts = channel.unary_unary(
                '/l3store.v1.L3Service/SearchSimilarPrompts',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsResponse.FromString,
                _registered_method=True)
        self.PrefetchBatch = channel.unary_unary(
                '/l3store.v1.L3Service/PrefetchBatch',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/l3store.v1.L3Service/GetStats',
                request_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class L3ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutKVBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKVBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKVBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKVBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutRAGObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRAGObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutSemanticEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSemanticEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilarPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrefetchBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_L3ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutKVBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.PutKVBlock,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockResponse.SerializeToString,
            ),
            'GetKVBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKVBlock,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockResponse.SerializeToString,
            ),
            'DeleteKVBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKVBlock,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockResponse.SerializeToString,
            ),
            'ListKVBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKVBlocks,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksResponse.SerializeToString,
            ),
            'PutRAGObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PutRAGObject,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectResponse.SerializeToString,
            ),
            'GetRAGObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRAGObject,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectResponse.SerializeToString,
            ),
            'PutSemanticEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.PutSemanticEntry,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryResponse.SerializeToString,
            ),
            'GetSemanticEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSemanticEntry,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryResponse.SerializeToString,
            ),
            'SearchSimilarPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarPrompts,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsResponse.SerializeToString,
            ),
            'PrefetchBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefetchBatch,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsRequest.FromString,
                    response_serializer=l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'l3store.v1.L3Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('l3store.v1.L3Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class L3Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutKVBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/PutKVBlock',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutKVBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKVBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/GetKVBlock',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetKVBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKVBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/DeleteKVBlock',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.DeleteKVBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKVBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/ListKVBlocks',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.ListKVBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutRAGObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/PutRAGObject',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutRAGObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRAGObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/GetRAGObject',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetRAGObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutSemanticEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/PutSemanticEntry',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PutSemanticEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSemanticEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/GetSemanticEntry',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetSemanticEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilarPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/SearchSimilarPrompts',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.SearchSimilarPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrefetchBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/PrefetchBatch',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.PrefetchBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/l3store.v1.L3Service/GetStats',
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsRequest.SerializeToString,
            l3store_dot_api_dot_proto_dot_l3__service__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
